apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: trading-bot
spec:
  type: ClusterIP
  clusterIP: None  # Headless
  selector:
    app: trading-bot
