apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: spy-options-bot
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "2000"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /volumes
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
