apiVersion: v1
data:
  ANOMALY_THRESHOLD: "0.3"
  IBKR_HOST: ibkr-gateway-service
  IBKR_PORT: "4003"
  LOG_LEVEL: INFO
  MAX_POSITIONS: "5"
  MAX_STRIKES_LIMIT: "5"
  SCAN_INTERVAL_SECONDS: "5"
  STRATEGY_TYPE: anomaly-arbitrage
  STRIKES_RANGE_PERCENT: "1.5"
  ATM_RANGE_PERCENT: "1.5"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: spy-bot
    meta.helm.sh/release-namespace: spy-options-bot
  creationTimestamp: "2026-01-15T21:51:08Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: bot-config
  namespace: spy-options-bot
  resourceVersion: "989924"
  uid: 655a2d70-8c8b-4cf5-94e8-bd13801491e9
