apiVersion: v1
kind: Service
metadata:
  name: ibkr-gateway-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: ibkr-gateway
spec:
  clusterIP: None
  selector:
    app: ibkr-gateway
  ports:
  - port: 4003
    targetPort: 4003
    protocol: TCP
    name: tws-api
