apiVersion: v1
kind: Service
metadata:
  name: detector
  namespace: spy-options-bot
  labels:
    app: detector
spec:
  selector:
    app: detector
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  type: ClusterIP